---
version: 3

images:
  base_image:
    name: ghcr.io/distronode/community-distronode-devtools:latest

dependencies:
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/dnf5
