---
blank_issues_enabled: true
contact_links:
  - name: 📝 Distronode Code of Conduct
    url: https://docs.distronode.com/distronode/latest/community/code_of_conduct.html?utm_medium=github&utm_source=issue_template_chooser
    about: django-distronode-base uses the Distronode Code of Conduct; ❤ Be nice to other members of the community. ☮ Behave.
