{
 "title": "api-demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Dispatcher",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dispatcher Availability",
     "type": "timeseries",
     "description": "Fraction of time dispatcher is listening for new messages",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      { "expr": "dispatcher_availability", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Dispatcher Workers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "dispatcher_pool_max_worker_count",
       "legendFormat": "__auto"
      },
      {
       "expr": "dispatcher_pool_active_task_count",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Dispatcher Pool Scale-Up Events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "dispatcher_pool_scale_up_events",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      { "expr": "api_database_connections_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Controller Version",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "api_system_info" }
     ]
    },
    {
     "title": "Controller Node Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 12, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "count(api_instance_info)", "legendFormat": "  " }
     ]
    }
   ]
  },
  {
   "title": "Jobs and Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "job status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      { "expr": "api_status_total", "legendFormat": "{{status}}" }
     ]
    },
    {
     "title": "Job Status per Instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      { "expr": "api_instance_status_total", "legendFormat": "{{node}}-{{status}}" }
     ]
    },
    {
     "title": "Dependency Manager Timings",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "dependency_manager__schedule_seconds",
       "legendFormat": "__auto"
      },
      {
       "expr": "dependency_manager_generate_dependencies_seconds",
       "legendFormat": "__auto"
      },
      {
       "expr": "dependency_manager_get_tasks_seconds",
       "legendFormat": "__auto"
      },
      {}
     ]
    },
    {
     "title": "Workflow Manager Timings",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "workflow_manager__schedule_seconds",
       "legendFormat": "__auto"
      },
      {}
     ]
    },
    {
     "title": "Remaining Instance Capacity",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "api_instance_remaining_capacity",
       "legendFormat": "remaining_capacity_{{hostname}}"
      }
     ]
    },
    {
     "title": "Consumed Instance Capacity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "targets": [
      { "expr": "api_instance_consumed_capacity", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Task Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task manager workload",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      { "expr": "task_manager_running_processed" },
      { "expr": "task_manager_pending_processed" },
      { "expr": "task_manager_tasks_blocked" },
      { "expr": "task_manager_tasks_started" }
     ]
    },
    {
     "title": "Task manager timings",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "task_manager_process_pending_tasks_seconds",
       "legendFormat": "__auto"
      },
      {
       "expr": "task_manager_process_running_tasks_seconds",
       "legendFormat": "__auto"
      },
      { "expr": "task_manager_get_tasks_seconds", "legendFormat": "__auto" },
      { "expr": "task_manager_commit_seconds", "legendFormat": "__auto" },
      { "expr": "task_manager__schedule_seconds", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Job Event Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg Job Event Processing Lag Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "callback_receiver_event_processing_avg_seconds",
       "legendFormat": "{{node}}-processing-avg-seconds"
      }
     ]
    },
    {
     "title": "Redis Queue Size vs. Job Events Processed/Minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "callback_receiver_events_queue_size_redis",
       "legendFormat": "{{node}}-redis-queue"
      },
      {
       "expr": "irate(callback_receiver_events_insert_db[1m])*60",
       "legendFormat": "{{node}}-job-event-processing-rate"
      }
     ]
    }
   ]
  }
 ]
}