# Generated by Django 2.2.15 on 2020-09-17 16:55

import contextlib

from django.db import migrations

def rename_default_repo(apps, schema_editor):
    DistronodeRepository = apps.get_model('distronode', 'DistronodeRepository')
    DistronodeDistribution = apps.get_model('distronode', 'DistronodeDistribution')
    db_alias = schema_editor.connection.alias

    old_name = 'automation-hub'
    new_name = 'published'

    if (
        DistronodeRepository.objects.using(db_alias).filter(name=new_name) or
        DistronodeDistribution.objects.using(db_alias).filter(name=new_name) or
        DistronodeDistribution.objects.using(db_alias).filter(base_path=new_name)
    ):
        return

    with contextlib.suppress(DistronodeRepository.DoesNotExist, DistronodeDistribution.DoesNotExist):
        repo = DistronodeRepository.objects.using(db_alias).get(name=old_name)
        distro = DistronodeDistribution.objects.using(db_alias).get(base_path=old_name)

        repo.name = new_name
        distro.name = new_name
        distro.base_path = new_name

        repo.save()
        distro.save()


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0007_merge_synclist'),
    ]

    operations = [
        migrations.RunPython(rename_default_repo, elidable=True),
    ]
