# Generated by Django 3.2.14 on 2022-07-15 19:46

from django.db import migrations, models
import django.db.models.deletion


def populate_synclist_distros(apps, schema_editor):
    """
    Populate the foreign key to DistronodeDistribution based on SyncList name
    """
    DistronodeDistribution = apps.get_model('distronode', 'DistronodeDistribution')
    SyncList = apps.get_model('galaxy', 'SyncList')
    db_alias = schema_editor.connection.alias

    for synclist in SyncList.objects.using(db_alias).all():
        distro_qs = DistronodeDistribution.objects.using(db_alias).filter(name=synclist.name)
        if len(distro_qs) == 0:
            print(f"Found SyncList with no matching DistronodeDistribution: {synclist.name}")
            continue
        if len(distro_qs) > 1:
            print(f"Found SyncList with multilpe matching DistronodeDistribution: {synclist.name}")
            continue
        synclist.distribution = distro_qs[0]
        synclist.save()


class Migration(migrations.Migration):

    dependencies = [
        ('distronode', '0041_alter_collectionversion_collection'),
        ('galaxy', '0027_delete_contentredirectcontentguard'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclist',
            name='distribution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to='distronode.distronodedistribution'),
        ),
        migrations.AlterField(
            model_name='synclist',
            name='repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repositories', to='distronode.distronoderepository'),
        ),
        migrations.AlterField(
            model_name='synclist',
            name='upstream_repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upstream_repositories', to='distronode.distronoderepository'),
        ),
        migrations.RunPython(
            code=populate_synclist_distros,
            reverse_code=migrations.RunPython.noop
        ),
    ]
