name: Upload logs
description: Upload logs from `make docker-compose` devel environment to GitHub as an artifact
inputs:
  log-filename:
    description: "*Unique* name of the log file"
    required: true
runs:
  using: composite
  steps:
    - name: Get API logs
      shell: bash
      run: |
        docker logs tools_api_1 > ${{ inputs.log-filename }}

    - name: Upload API logs as artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-compose-logs
        path: ${{ inputs.log-filename }}
